// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Details about an unspecified validation that doesn't fit other categories.</p>
#[non_exhaustive]
#[cfg_attr(feature = "serde-serialize", derive(::serde::Serialize))]
#[cfg_attr(feature = "serde-deserialize", derive(::serde::Deserialize))]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct UnspecifiedFlowValidationDetails {}
impl UnspecifiedFlowValidationDetails {
    /// Creates a new builder-style object to manufacture [`UnspecifiedFlowValidationDetails`](crate::types::UnspecifiedFlowValidationDetails).
    pub fn builder() -> crate::types::builders::UnspecifiedFlowValidationDetailsBuilder {
        crate::types::builders::UnspecifiedFlowValidationDetailsBuilder::default()
    }
}

/// A builder for [`UnspecifiedFlowValidationDetails`](crate::types::UnspecifiedFlowValidationDetails).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct UnspecifiedFlowValidationDetailsBuilder {}
impl UnspecifiedFlowValidationDetailsBuilder {
    /// Consumes the builder and constructs a [`UnspecifiedFlowValidationDetails`](crate::types::UnspecifiedFlowValidationDetails).
    pub fn build(self) -> crate::types::UnspecifiedFlowValidationDetails {
        crate::types::UnspecifiedFlowValidationDetails {}
    }
}
