// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Rtmp Caption Info Destination Settings
#[non_exhaustive]
#[cfg_attr(feature = "serde-serialize", derive(::serde::Serialize))]
#[cfg_attr(feature = "serde-deserialize", derive(::serde::Deserialize))]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct RtmpCaptionInfoDestinationSettings {}
impl RtmpCaptionInfoDestinationSettings {
    /// Creates a new builder-style object to manufacture [`RtmpCaptionInfoDestinationSettings`](crate::types::RtmpCaptionInfoDestinationSettings).
    pub fn builder() -> crate::types::builders::RtmpCaptionInfoDestinationSettingsBuilder {
        crate::types::builders::RtmpCaptionInfoDestinationSettingsBuilder::default()
    }
}

/// A builder for [`RtmpCaptionInfoDestinationSettings`](crate::types::RtmpCaptionInfoDestinationSettings).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct RtmpCaptionInfoDestinationSettingsBuilder {}
impl RtmpCaptionInfoDestinationSettingsBuilder {
    /// Consumes the builder and constructs a [`RtmpCaptionInfoDestinationSettings`](crate::types::RtmpCaptionInfoDestinationSettings).
    pub fn build(self) -> crate::types::RtmpCaptionInfoDestinationSettings {
        crate::types::RtmpCaptionInfoDestinationSettings {}
    }
}
