// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Smpte Tt Destination Settings
#[non_exhaustive]
#[cfg_attr(feature = "serde-serialize", derive(::serde::Serialize))]
#[cfg_attr(feature = "serde-deserialize", derive(::serde::Deserialize))]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct SmpteTtDestinationSettings {}
impl SmpteTtDestinationSettings {
    /// Creates a new builder-style object to manufacture [`SmpteTtDestinationSettings`](crate::types::SmpteTtDestinationSettings).
    pub fn builder() -> crate::types::builders::SmpteTtDestinationSettingsBuilder {
        crate::types::builders::SmpteTtDestinationSettingsBuilder::default()
    }
}

/// A builder for [`SmpteTtDestinationSettings`](crate::types::SmpteTtDestinationSettings).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct SmpteTtDestinationSettingsBuilder {}
impl SmpteTtDestinationSettingsBuilder {
    /// Consumes the builder and constructs a [`SmpteTtDestinationSettings`](crate::types::SmpteTtDestinationSettings).
    pub fn build(self) -> crate::types::SmpteTtDestinationSettings {
        crate::types::SmpteTtDestinationSettings {}
    }
}
