// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>The connector metadata specific to Upsolver.</p>
#[non_exhaustive]
#[cfg_attr(feature = "serde-serialize", derive(::serde::Serialize))]
#[cfg_attr(feature = "serde-deserialize", derive(::serde::Deserialize))]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct UpsolverMetadata {}
impl UpsolverMetadata {
    /// Creates a new builder-style object to manufacture [`UpsolverMetadata`](crate::types::UpsolverMetadata).
    pub fn builder() -> crate::types::builders::UpsolverMetadataBuilder {
        crate::types::builders::UpsolverMetadataBuilder::default()
    }
}

/// A builder for [`UpsolverMetadata`](crate::types::UpsolverMetadata).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct UpsolverMetadataBuilder {}
impl UpsolverMetadataBuilder {
    /// Consumes the builder and constructs a [`UpsolverMetadata`](crate::types::UpsolverMetadata).
    pub fn build(self) -> crate::types::UpsolverMetadata {
        crate::types::UpsolverMetadata {}
    }
}
