// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>Deletes the CloudFormation summary step output.</p>
#[non_exhaustive]
#[cfg_attr(feature = "serde-serialize", derive(::serde::Serialize))]
#[cfg_attr(feature = "serde-deserialize", derive(::serde::Deserialize))]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteCloudFormationStepOutput {}
impl DeleteCloudFormationStepOutput {
    /// Creates a new builder-style object to manufacture [`DeleteCloudFormationStepOutput`](crate::types::DeleteCloudFormationStepOutput).
    pub fn builder() -> crate::types::builders::DeleteCloudFormationStepOutputBuilder {
        crate::types::builders::DeleteCloudFormationStepOutputBuilder::default()
    }
}

/// A builder for [`DeleteCloudFormationStepOutput`](crate::types::DeleteCloudFormationStepOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct DeleteCloudFormationStepOutputBuilder {}
impl DeleteCloudFormationStepOutputBuilder {
    /// Consumes the builder and constructs a [`DeleteCloudFormationStepOutput`](crate::types::DeleteCloudFormationStepOutput).
    pub fn build(self) -> crate::types::DeleteCloudFormationStepOutput {
        crate::types::DeleteCloudFormationStepOutput {}
    }
}
