// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// <p>A structure used to reboot the device.</p>
#[non_exhaustive]
#[cfg_attr(feature = "serde-serialize", derive(::serde::Serialize))]
#[cfg_attr(feature = "serde-deserialize", derive(::serde::Deserialize))]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct Reboot {}
impl Reboot {
    /// Creates a new builder-style object to manufacture [`Reboot`](crate::types::Reboot).
    pub fn builder() -> crate::types::builders::RebootBuilder {
        crate::types::builders::RebootBuilder::default()
    }
}

/// A builder for [`Reboot`](crate::types::Reboot).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct RebootBuilder {}
impl RebootBuilder {
    /// Consumes the builder and constructs a [`Reboot`](crate::types::Reboot).
    pub fn build(self) -> crate::types::Reboot {
        crate::types::Reboot {}
    }
}
